### ISSUE TITLE
Doesnt work with spine-hx 3.7 :(

### ISSUE THREAD

**Issue by CrazyFlasher** [rainyt/OpenFLSpine#5]
`Error:(50, 12) spine.Skeleton has no field setFlipY`

**Comment by rainyt** [comment]
Currently available in version 3.6. i did not notice that there is a version of 3.7 for haxelib.

**Comment by CrazyFlasher** [comment]
Yes. There is a 3.7 branch of [spine-hx](https://github.com/jeremyfa/spine-hx/tree/3.7). Could you please check? I guess it would be much faster for you to support 3.7. I can send test animated skeleton to your email if needed.
Difference is only in armature (skeleton) setup.

**Comment by rainyt** [comment]
I have already implemented the compatible version 3.7.0 and can execute `haxelib update openfl-spine`.

**Comment by CrazyFlasher** [comment]
My animation is still broken :(
[sesame_shiba.zip](https://github.com/rainyt/OpenFLSpine/files/3615857/sesame_shiba.zip)

May be this issue is related to spine-hx? Can you check please

**Comment by CrazyFlasher** [comment]
This issue happens if "Stip whitespace" is on
![image](https://user-images.githubusercontent.com/1607138/64954414-2ccb7e00-d88e-11e9-9092-a79fce9dc705.png)

**Comment by rainyt** [comment]
This seems to be a problem with the exported data format, and the resources running by samples can be displayed normally. I am not sure if there is any implementation of arbitrary animation data that I am ignoring.

PS：strip whitespace X strip whitespace Y
Regarding this, i need some time to see if I can solve this problem.

**Comment by CrazyFlasher** [comment]
![image](https://user-images.githubusercontent.com/1607138/64956113-846be880-d892-11e9-845d-25c7e319af94.png)
White space data can be seen in atlas:
**orig** - is the full size of image with transparent part
**size** - is stripped size of image (without transparency)
**offset** - x and y offset of the image in full image with transparecy

Hope that would help :)

**Comment by rainyt** [comment]
![image](https://user-images.githubusercontent.com/9693090/65015969-a4b0ab80-d955-11e9-935d-30742f36d902.png)
It seems to be getting better, but is there something missing on the puppy's leg? is this normal?

**Comment by rainyt** [comment]
![image](https://user-images.githubusercontent.com/9693090/65016520-12a9a280-d957-11e9-96a3-f47b393b83ba.png)
I believe it has been fixed.

**Comment by CrazyFlasher** [comment]
Something is still broken.
Now even skeleton with stip whitspace off are broken (which worked fine in 1.4.1 version)
Expected:
![image](https://user-images.githubusercontent.com/1607138/65018680-58a03f80-d932-11e9-8e08-e4ab9302f835.png)
Actual:
![image](https://user-images.githubusercontent.com/1607138/65018694-5fc74d80-d932-11e9-8dab-6fbf18519b94.png)

[stip_white_space_on.zip](https://github.com/rainyt/OpenFLSpine/files/3619702/stip_white_space_on.zip)
[strip_white_space_off.zip](https://github.com/rainyt/OpenFLSpine/files/3619703/strip_white_space_off.zip)

**Comment by rainyt** [comment]
I resubmitted the revised version and ignored the images without offset data. Can update the 1.4.4 version to try

**Comment by CrazyFlasher** [comment]
Some stuff still broken. You can check example I've attached

**Comment by rainyt** [comment]
![image](https://user-images.githubusercontent.com/9693090/65022119-f6136780-d962-11e9-9cd2-93e529bf0cd7.png)
Fix this, check please. openfl-spine 1.4.5 version.

**Comment by CrazyFlasher** [comment]
Looks much better now!
But still 2 animations are broken (attached):

Expected:
![image](https://user-images.githubusercontent.com/1607138/65022681-0c58fd80-d93a-11e9-89e3-00d959d3a799.png)

Actual:
![image](https://user-images.githubusercontent.com/1607138/65022660-04995900-d93a-11e9-9fb4-8dc335915fa8.png)

[strip_white_space_off.zip](https://github.com/rainyt/OpenFLSpine/files/3619959/strip_white_space_off.zip)
[stip_white_space_on.zip](https://github.com/rainyt/OpenFLSpine/files/3619961/stip_white_space_on.zip)

**Comment by rainyt** [comment]
![image](https://user-images.githubusercontent.com/9693090/65025772-e5b2bb00-d969-11e9-8c7b-93f857acf13e.png)

Some animations are fixed, but the following sample seems to have a new problem. I am not sure if there is any problem with the animation. Can you circumvent it?

Fix: https://github.com/rainyt/OpenFLSpine/commit/960aa366745613b710aaf8e3e2b1b0142a97e6e6
https://github.com/rainyt/OpenFLSpine/commit/cff3362009ce7eabccf16447f6c3db66b961cf7c

**Comment by CrazyFlasher** [comment]
Well, it works fine if strip is off.
However, almost everything works fine now with strip on!
Thank you!

**Comment by CrazyFlasher** [comment]
Those 2 symbols have more than 1 animations. May be that is the issue?

**Comment by rainyt** [comment]
I'm not sure, but I think it's ok to hide the back letters in the animation.

**Comment by CrazyFlasher** [comment]
But it works fine if strip whitespace turned off
